[general]
# How many MCS the simulation will run for.
time-steps = 2048
# Seed for the RNG.
# Use `0` to pick a random seed.
seed = 1241254152

[io]
# Output directory for files.
outdir = "benches/model_outputs/full_lattice"
# Flag used to delete contents of `outdir` if it exists.
replace-outdir = true
# Period (in MCS) with which to save an image of the simulation.
image-period = 2048

[environment]
# Width of the lattice.
width = 128
# Height of the lattice.
height = 128
# Whether to create a solid border around the cell lattice.
# Should not be used with `neigh_r` > 1.
enclose = false
# Number of starting cells in the environment.
n-cells = 1024
# Cell parameters
# Starting cell area.
cell-start-area = 64
# Target cell area.
cell-target-area = 64
cell-div-area = 128
cell-update-period = 1000000
# Radius of the neighbourhood.
neigh-r = 1

[cellular-automata]
# Boltzmann temperature.
# Increases likelihood of unfavourable copy attempts being accepted.
boltz-t = 16
# Scaler constant for area deviation penalties.
size-lambda = 1
# Scaler constant for chemotaxis bias.
chemotaxis-mu = 4

[cellular-automata.adhesion]
type = "static-adhesion"
# Adhesion energy at cell-cell interfaces.
cell-energy = 16
# Adhesion energy at cell-medium interfaces.
medium-energy = 16
# Adhesion energy at cell-solid interfaces.
solid-energy = 16

[movie]
show = false
width = 320
height = 320
frame-period = 50