[general]
# How many MCS the simulation will run for.
time-steps = 2048
# Seed for the RNG.
# Use `0` to pick a random seed.
seed = 1241254152

[io]
# Output directory for files.
outdir = "benches/model_outputs/full_lattice"
# Flag used to delete contents of `outdir` if it exists.
replace-outdir = true
# Period (in MCS) with which to save an image of the simulation.
image-period = 2048

[io.plots]
# Defines which plots to make and in what order.
# Options are:
#   - "spin":   Plots lattice spins.
#   - "center": Plots cell centers.
#   - "clones": Plots will cells are attached.
order = ["spin"]
# With which color to plot solid objects.
solid-color = "#000000"
# With which color to plot the medium.
# Ommit to make the medium transparent.
# medium-color = "#ffffff"
# With which color to plot the centers of cells.
center-color = "#00ff00"
# With which color to plot the connections between cell clones.
clones-color = "#ff0000"

[environment]
# Width of the lattice.
width = 128
# Height of the lattice.
height = 128
# Whether to create a solid border around the cell lattice.
# Should not be used with `neigh_r` > 1.
enclose = false
neigh-r = 1
# Number of starting cells in the environment.
starting-cells = 1024
# Maximum number of cells allowed in the simulation.
# Cell division is prevented if it would cause the cell population to exceed this threshold.
max-cells = 1024
# Starting cell area.
cell-start-area = 64
# How many times the cell putative radius will be scaled when searching for the cell's positions.
# Decreasing this parameter improves performance but may lead to critical warnings reporting that not
# cell postitions could be found.
cell-search-radius = 2.5
# Period (in MCS) with which the environment is updated.
# This includes cell growth (by 1 area unit), genomic parameters, and reproduction.
update-period = 32

[environment.cell]
# Target cell area.
target-area = 64
# Cell area before division.
div-area = 128
# Set to `false` to disable division.
# [default = true]
divide = true

[cellular-automata]
# Boltzmann temperature.
# Increases likelihood of unfavourable copy attempts being accepted.
boltz-t = 16
# Scaler constant for area deviation penalties.
size-lambda = 1
# Scaler constant for chemotaxis bias.
chemotaxis-mu = 4

[cellular-automata.adhesion]
type = "static-adhesion"
# Adhesion energy at cell-cell interfaces.
cell-energy = 16
# Adhesion energy at cell-medium interfaces.
medium-energy = 16
# Adhesion energy at cell-solid interfaces.
solid-energy = 16

[io.movie]
show = false
width = 320
height = 320
frame-period = 50