[general]
# How many MCS the simulation will run for.
time-steps = 8192
# Seed for the RNG.
# Omit to pick a random seed.
seed = 1241254152
# Period (in MCS) with which to check and execute dispersion events.
dispersion-period = 1000

[pond]
# Number of ponds to create.
n-ponds = 1
# Width of the lattice.
width = 128
# Height of the lattice.
height = 128
# Whether to create a solid border around the cell lattice.
# Should not be used with `neigh_r` > 1.
# [default = false]
enclose = false
# Radius of the neighbourhood.
neigh-r = 1

[cell]
# Number of starting cells in the environment.
starting-cells = 64
# Maximum number of cells allowed in the environment.
# Cell division is prevented if it would cause the cell population to exceed this threshold.
max-cells = 1024
# How many times to enlarge the cells' putative radii when searching for them in the environment.
# Decreasing this parameter improves performance but may lead to critical warnings reporting that not
# all cell postitions could be found.
search-radius = 3.0
# Starting cell area.
starting-area = 64
# Target cell area.
target-area = 64
# Cell area before division.
div-area = 128
# Set to `false` to disable division.
# [default = true]
divide = true
# Set to `false` to disable migration.
# [default = true]
migrate = true
# Period (in MCS) with which the cell is updated.
# This includes cell growth, genome updates and reproduction.
update-period = 32

[cell.genome]
# Number of regulatory genes in the cell's GRN.
n-regulatory = 2
# Mutation rate for each GRN parameter.
mutation-rate = 0.01
# Standard deviation of the GRN parameter mutations.
mutation-std = 0.01

[ca]
# Boltzmann temperature.
# Increases likelihood of unfavourable copy attempts being accepted.
boltz-t = 16.0
# Scaler constant for area deviation penalties.
size-lambda = 1.0
# Scaler constant for chemotaxis bias.
chemotaxis-mu = 4.0

[ca.adhesion]
# Adhesion energy at cell-cell interfaces of clonal cells.
clone-energy = 8.0
# Adhesion energy at cell-cell interfaces of non-clonal cells.
cell-energy = 16.0
# Adhesion energy at cell-medium interfaces.
medium-energy = 16.0
# Adhesion energy at cell-solid interfaces.
solid-energy = 16.0

[io]
# Output directory for files.
outdir = "model/examples/64_cells"
# Flag used to delete contents of `outdir` if it exists.
# [default = false]
replace-outdir = true
# Period (in MCS) with which to save an image of the simulation.
image-period = 2048
# Format used to save images.
# Supports any format supported by the `image` crate.
# [default = "webp"]
image-format = "webp"

[io.data]
# Period (in MCS) with which to save a parquet file containing cell attributes.
cell-period = 2048
# Period (in MCS) with which to save a JSON file in the node-link format containing the cell's genomes.
genome-period = 4096
# Period (in MCS) with which to save a JSON file containing the cell lattices for each pond.
lattice-period = 4096

[io.plot]
# Defines which plots to make and in what order.
# Options are:
#   - "spin":         Plots lattice spins.
#   - "center":       Plots cell centers.
#   - "clones":       Plots will cells are attached.
#   - "border":       Plots cell borders.
#   - "chem":         Plots the chem gradient.
#   - "chem-center":  Plots the perceived center of the chem gradient.
#   - "cell-type":    Plots the cell type of cells.
order = ["chem", "cell-type", "border"]
# With which color to plot solid objects.
solid-color = "#000000"
# With which color to plot the medium.
# Ommit to make the medium transparent.
# medium-color = "#ffffff"
# With which color to plot the centers of cells.
center-color = "#00ff00"
# With which color to plot the perceived center of chem of cells.
chem-center-color = "#00ff00"
# With which color to plot the border of cells.
border-color = "#000000"
# With which color to plot the connections between cell clones.
clones-color = "#ff0000"
# Set to true to display all clone pairs, even those span across the lattice due to periodic boundaries.
# [default = false]
all-clones = false
# With which color to plot the minimum area in the cell population.
area-min-color = "#ff00ff"
# With which color to plot the maximum area in the cell population.
area-max-color = "#ffff00"
# With which color to plot the minimum value for the chem in the environment.
chem-min-color = "#000000"
# With which color to plot the maximum value for the chem in the environment.
chem-max-color = "#ffffff"
# With which color to plot migrating cells.
migrating-color = "#b30000"
# With which color to plot dividing cells.
dividing-color = "#045a8d"

[io.movie]
# Whether the real-time movie should be shown or not.
# This will slow down the simulation a lot.
# [default = false]
show = true
# Width of the movie window.
width = 320
# Height of the movie window.
height = 320
# How many MCS to skip between the displayed frames.
frame-period = 100