[general]
# How many MCS the simulation will run for.
time-steps = 8192
# Seed for the RNG.
# Omit to pick a random seed.
seed = 1241254152

[pond]
# Width of the lattice.
width = 128
# Height of the lattice.
height = 128
# Whether to create a solid border around the cell lattice.
# Should not be used with `neigh_r` > 1.
# [default = false]
enclose = true
# Radius of the neighbourhood.
neigh-r = 1
# Period with which the gradient is erased and centered around a new location.
season-duration = 512
# Chemical concentration at which the fitness of cells is 0.5.
# The chemical concentration is the diagonal of the lattice - the distance of a site from the centre of the gradient.
half-fitness = 50.0
# Number of MCSperformed between rounds of cell divisions when a single cell is selected more than once.
reproduction-steps = 5

[cell]
# Number of starting cells in the environment.
starting-cells = 64
# Maximum number of cells allowed in the environment.
# Cell division is prevented if it would cause the cell population to exceed this threshold.
max-cells = 1024
# How many times to enlarge the cells' putative radii when searching for them in the environment.
# Decreasing this parameter improves performance but may lead to critical warnings reporting that not
# all cell postitions could be found.
search-radius = 3.0
# Starting cell area.
starting-area = 64
# Target cell area.
target-area = 64
# Cell area before division.
div-area = 128
# Target cell perimeter.
target-perimeter = 120
# Set to `false` to disable division.
# [default = true]
divide = true

[cell.genome]
# Number of regulatory genes in the cell's GRN.
n-regulatory = 2
# Mutation rate for each GRN parameter.
mutation-rate = 0.01
# Number of ligands and receptors in the genome (total size is double this parameter).
length = 8

[potts]
# Boltzmann temperature.
# Increases likelihood of unfavourable copy attempts being accepted.
boltz-t = 16.0
# Scaler constant for area deviation penalties.
size-lambda = 1.0
# Scaler constant for perimeter deviation penalties.
perimeter-lambda = 1.0
# Minimum strength of chemotaxis bias when cells experience a chem. concentration = 0 in the contact case
# (relative to the bias at max concentration, which is the full effect of the Act term).
# Use 0 to deactivate chemotaxis at low concentrations, and 1 to maintain full chemotaxis throughout the lattice.
chemotaxis-min = 0.5
# Max act value on a brand-new cell protusion.
act-max = 40
# Scaler constant for chemotaxis bias.
act-lambda = 20.0

[potts.adhesion]
# Minimum adhesion energy at cell-cell interfaces (summed to adhesion from adh. proteins).
cell-energy = 12.0
# Adhesion energy at cell-medium interfaces.
medium-energy = 16.0
# Adhesion energy at cell-solid interfaces.
solid-energy = 16.0

[io]
# Output directory for files.
outdir = "model/examples/64_cells"
# Flag used to delete contents of `outdir` if it exists.
# [default = false]
replace-outdir = true
# Period (in MCS) with which to log information about the simulation to stdout.
info-period = 2048
# Period (in MCS) with which to save an image of the simulation.
image-period = 2048
# Format used to save images.
# Supports any format supported by the `image` crate.
# [default = "webp"]
image-format = "webp"

[io.data]
# Period (in MCS) with which to save the cell attributes as a parquet file.
cells-period = 2048
# Period (in MCS) with which to save the cells' genomes as a JSON file.
genomes-period = 4096
# Period (in MCS) with which to save a parquet file containing the cell lattice.
lattice-period = 4096

[io.plot]
# Defines which plots to make and in what order.
# Options are:
#   - "spin":         Plots lattice spins.
#   - "center":       Plots cell centers.
#   - "border":       Plots cell borders.
#   - "chem":         Plots the chem gradient.
#   - "chem-center":  Plots the perceived center of the chem gradient.
#   - "area":         Plots the relative area of cells.
#   - "act":          Plots the activation of cells' membranes.
order = ["chem", "act", "border"]
# With which color to plot solid objects.
solid-color = "#000000"
# With which color to plot the medium.
# Ommit to make the medium transparent.
# medium-color = "#ffffff"
# With which color to plot the centers of cells.
center-color = "#00ff00"
# With which color to plot the perceived center of chem of cells.
chem-center-color = "#00ff00"
# With which color to plot the border of cells.
border-color = "#000000"
# With which color to plot the minimum area in the cell population.
area-min-color = "#ff00ff"
# With which color to plot the maximum area in the cell population.
area-max-color = "#ffff00"
# With which color to plot the minimum value for the chem in the environment.
chem-min-color = "#000000"
# With which color to plot the maximum value for the chem in the environment.
chem-max-color = "#ffffff"
# With which color to plot the minimum value for the act in the environment.
act-min-color = "#ff00ff"
# With which color to plot the maximum value for the act in the environment.
act-max-color = "#ffff00"
# With which color to plot migrating cells.
migrating-color = "#b30000"
# With which color to plot dividing cells.
dividing-color = "#045a8d"

[io.movie]
# Whether the real-time movie should be shown or not.
# This will slow down the simulation a lot.
# [default = false]
show = true
# Width of the movie window.
width = 320
# Height of the movie window.
height = 320
# How many MCS to skip between the displayed frames.
frame-period = 100